### ISSUE TITLE
configure github actions

### ISSUE THREAD

**Issue by paschalidi** [small-ads/core#14]
On very commit that is pushed on a PR we want to run the command `npm run lint` on the root directory. We want to be doing that using github actions and then having the result being displayed for us on the PR itself

**Comment by AdrianValdes** [comment]
So we will want to run the command `npm run lint` just for PRs to main, is that right? I have it like so now:

```
on:
  pull_request:
    branches: [ main ]

```
    
  I thought to run the actions just on pull_requests because of two reasons:
  
   1. We cannot push to main
   2. We don't have a develop branch where we include a rule like
   
```
   on:
     push:
      branches:
        - develop/*
```

**Comment by AdrianValdes** [comment]
This is the whole file, (I don't know if is right to paste the file here):

```
name: PR Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint types and code
      run: npm lint
```
